<script setup></script>
<template>
  <div style="overflow-y: auto;height: 100%;">
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div>页面</div>
    <div style="height: 1.44rem;"></div>
  </div>
</template>
<style scoped lang="scss"></style>